set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'timvw/tmux-assistant-resurrect'

set -g @continuum-restore 'off'
set -g @continuum-save-interval '5'

set -g @resurrect-processes 'watch'

run '~/.config/tmux/plugins/tpm/tpm'
